-- ═══════════════════════════════════════════════════════
-- MIGRATION PART 10 (files 91 to 99 of 99)
-- Execute in SQL Editor of Supabase Dashboard
-- ═══════════════════════════════════════════════════════


-- ── Migration: 20260327000013_seed_pjecalc_2026_tabelas.sql ──


-- ============================================================
-- SEED: Tabelas de Referência 2026
-- Salário mínimo, INSS, Seguro-Desemprego, Salário-Família
--
-- Fonte: Decreto 12.302/2024 (SM 2025=1518), estimativas 2026
-- baseadas no INPC acumulado 2025 (~6.84%) aplicado às tabelas.
-- Valores INSS: EC 103/2019 (sistema progressivo).
-- ============================================================

-- ============================================================
-- SALÁRIO MÍNIMO 2026
-- Decreto publicado em jan/2026 (estimativa INPC ≈ 6.84%)
-- ============================================================
INSERT INTO public.pjecalc_salario_minimo (competencia, valor)
VALUES
('2026-01-01', 1622.00)
ON CONFLICT DO NOTHING;

-- ============================================================
-- INSS FAIXAS 2026 — EC 103/2019 (Sistema Progressivo)
-- Tabela reajustada com base no SM 2026 = R$ 1.622,00
-- faixa 1: até 1 SM @ 7,5%
-- faixa 2: até ~1,76 SM @ 9%
-- faixa 3: até ~2,65 SM @ 12%
-- faixa 4: até ~5,14 SM @ 14%  (teto INSS)
-- ============================================================
INSERT INTO public.pjecalc_inss_faixas
  (competencia_inicio, competencia_fim, faixa, valor_ate, aliquota)
VALUES
('2026-01-01','2026-12-31',1, 1622.00, 0.075),
('2026-01-01','2026-12-31',2, 2857.16, 0.090),
('2026-01-01','2026-12-31',3, 4287.01, 0.120),
('2026-01-01','2026-12-31',4, 8341.15, 0.140)
ON CONFLICT DO NOTHING;

-- ============================================================
-- SEGURO-DESEMPREGO 2026 (Res. CODEFAT — estimativa)
-- Fórmula: parcela = valor_soma + (salario - valor_inicial) × percentual/100
-- Teto estimado com base em INPC 2025 sobre 2025 teto
-- ============================================================
INSERT INTO public.pjecalc_seguro_desemprego
  (competencia, faixa, valor_inicial, valor_final, percentual, valor_soma, valor_piso, valor_teto)
VALUES
('2026-01-01',1,    0.00, 1949.97, 80.00,    0.00, 1622.00, 3085.38),
('2026-01-01',2, 1949.97, 3249.94, 50.00, 1559.98, 1622.00, 3085.38),
('2026-01-01',3, 3249.94,999999.0, 40.00, 2209.97, 1622.00, 3085.38)
ON CONFLICT (competencia, faixa) DO NOTHING;

-- ============================================================
-- SALÁRIO-FAMÍLIA 2026 (Portaria MF — estimativa INPC)
-- 2025: faixa 1 até 1.819,26 → R$ 62,04/filho
--       faixa 2 acima → R$ 43,71/filho
-- 2026 ajustado por ~6.84%:
-- ============================================================
INSERT INTO public.pjecalc_salario_familia
  (competencia, faixa, valor_inicial, valor_final, valor_cota)
VALUES
('2026-01-01',1,   0.00, 1943.47, 66.28),
('2026-01-01',2,1943.47, 2915.21, 46.70)
ON CONFLICT (competencia, faixa) DO NOTHING;


-- ── Migration: 20260328000014_p0_fixes_citacao_dobrar_determinismo.sql ──


-- ============================================================
-- P0 FIXES — Paridade com PJe-Calc
-- 1. data_citacao: adiciona coluna real em pjecalc_calculos,
--    corrige VIEW pjecalc_dados_processo (estava mapeando
--    data_ajuizamento incorretamente), atualiza trigger.
-- 2. dobrar_valor_devido: adiciona coluna em pjecalc_verba_base,
--    expõe na VIEW pjecalc_verbas, atualiza trigger de INSERT.
-- ============================================================

-- ============================================================
-- 1. ADICIONAR data_citacao em pjecalc_calculos
-- ============================================================
ALTER TABLE public.pjecalc_calculos
  ADD COLUMN IF NOT EXISTS data_citacao TEXT;

-- ============================================================
-- 2. CORRIGIR VIEW pjecalc_dados_processo
--    Antes: c.data_ajuizamento::text AS data_citacao  ← ERRADO
--    Depois: c.data_citacao AS data_citacao           ← CORRETO
-- ============================================================
CREATE OR REPLACE VIEW public.pjecalc_dados_processo AS
SELECT
  c.id,
  c.case_id,
  c.processo_cnj        AS numero_processo,
  c.reclamante_nome,
  c.reclamante_cpf,
  c.reclamado_nome      AS reclamada_nome,
  c.reclamado_cnpj      AS reclamada_cnpj,
  c.vara,
  c.reclamado_nome      AS reclamado,
  NULL::text            AS perito,
  NULL::text            AS funcao,
  c.data_citacao,                     -- ← coluna real (não mais data_ajuizamento)
  c.created_at,
  c.updated_at
FROM public.pjecalc_calculos c;

ALTER VIEW public.pjecalc_dados_processo SET (security_invoker = on);

-- ============================================================
-- 3. ATUALIZAR trigger pjecalc_dp_ioi para persistir data_citacao
-- ============================================================
CREATE OR REPLACE FUNCTION public.pjecalc_dp_ioi()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE v_cid UUID;
BEGIN
  v_cid := pjecalc_get_calculo_id(NEW.case_id);
  UPDATE public.pjecalc_calculos SET
    processo_cnj   = COALESCE(NEW.numero_processo, processo_cnj),
    reclamante_nome= COALESCE(NEW.reclamante_nome, reclamante_nome),
    reclamante_cpf = COALESCE(NEW.reclamante_cpf, reclamante_cpf),
    reclamado_nome = COALESCE(NEW.reclamada_nome, reclamado_nome),
    reclamado_cnpj = COALESCE(NEW.reclamada_cnpj, reclamado_cnpj),
    vara           = COALESCE(NEW.vara, vara),
    data_citacao   = COALESCE(NEW.data_citacao, data_citacao),   -- ← NOVO
    updated_at     = now()
  WHERE id = v_cid;
  NEW.id := v_cid;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS pjecalc_dp_insert ON public.pjecalc_dados_processo;
DROP TRIGGER IF EXISTS pjecalc_dp_update ON public.pjecalc_dados_processo;

CREATE TRIGGER pjecalc_dp_insert
  INSTEAD OF INSERT ON public.pjecalc_dados_processo
  FOR EACH ROW EXECUTE FUNCTION public.pjecalc_dp_ioi();

CREATE TRIGGER pjecalc_dp_update
  INSTEAD OF UPDATE ON public.pjecalc_dados_processo
  FOR EACH ROW EXECUTE FUNCTION public.pjecalc_dp_ioi();

-- ============================================================
-- 4. ADICIONAR dobrar_valor_devido em pjecalc_verba_base
-- ============================================================
ALTER TABLE public.pjecalc_verba_base
  ADD COLUMN IF NOT EXISTS dobrar_valor_devido BOOLEAN DEFAULT false;

-- ============================================================
-- 5. RECONSTRUIR pjecalc_verbas VIEW para expor dobrar_valor_devido
--    (mantém todos os campos de migration 000010)
-- ============================================================
DROP TRIGGER IF EXISTS pjecalc_verbas_instead_insert ON public.pjecalc_verbas;
DROP TRIGGER IF EXISTS pjecalc_verbas_instead_delete ON public.pjecalc_verbas;
DROP VIEW IF EXISTS public.pjecalc_verbas;

CREATE OR REPLACE VIEW public.pjecalc_verbas AS
SELECT
  v.id,
  c.case_id,
  v.calculo_id,
  v.nome,
  v.codigo,
  v.caracteristica,
  v.periodicidade                            AS ocorrencia_pagamento,
  CASE
    WHEN v.verba_principal_id IS NOT NULL THEN 'reflexa'
    ELSE 'principal'
  END                                         AS tipo,
  v.multiplicador,
  v.divisor                                   AS divisor_informado,
  v.periodo_inicio::text                      AS periodo_inicio,
  v.periodo_fim::text                         AS periodo_fim,
  v.ordem,
  v.ativa,
  v.incide_inss,
  v.incide_fgts,
  v.incide_ir,
  v.verba_principal_id,
  v.valor,
  v.valor_informado_devido,
  v.valor_informado_pago,
  v.hist_salarial_nome,
  -- Engine-critical fields (from migration 000010)
  v.divisor_tipo,
  v.quantidade_tipo,
  v.quantidade_valor,
  v.fracao_mes_modo,
  v.compor_principal,
  v.gerar_principal,
  v.gerar_reflexo,
  v.excluir_falta_justificada,
  v.excluir_falta_nao_justificada,
  v.excluir_ferias_gozadas,
  v.comportamento_reflexo,
  v.periodo_media_reflexo,
  v.quantidade_proporcionalizar,
  v.hora_noturna_ficticia,
  v.constante_mensal,
  -- P0 FIX: dobrar_valor_devido now exposed
  v.dobrar_valor_devido,
  -- base_calculo JSON
  jsonb_build_object(
    'historicos', COALESCE(
      (SELECT jsonb_agg(hs.id)
       FROM public.pjecalc_hist_salarial hs
       WHERE hs.calculo_id = v.calculo_id AND hs.nome = v.hist_salarial_nome),
      '[]'::jsonb
    ),
    'tabelas', COALESCE(to_jsonb(v.base_tabelas), '[]'::jsonb),
    'verbas', CASE
      WHEN v.verba_principal_id IS NOT NULL THEN jsonb_build_array(v.verba_principal_id)
      ELSE '[]'::jsonb
    END
  ) AS base_calculo,
  '{}'::jsonb AS incidencias,
  v.observacoes,
  v.created_at,
  v.updated_at
FROM public.pjecalc_verba_base v
JOIN public.pjecalc_calculos c ON v.calculo_id = c.id;

ALTER VIEW public.pjecalc_verbas SET (security_invoker = on);

-- ============================================================
-- 6. ATUALIZAR pjecalc_verbas_ioi para persistir dobrar_valor_devido
-- ============================================================
CREATE OR REPLACE FUNCTION public.pjecalc_verbas_ioi()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_cid UUID;
  v_tabelas text[];
BEGIN
  v_cid := pjecalc_get_calculo_id(NEW.case_id);

  IF NEW.base_calculo IS NOT NULL AND NEW.base_calculo ? 'tabelas' THEN
    SELECT array_agg(t::text) INTO v_tabelas
    FROM jsonb_array_elements_text(NEW.base_calculo->'tabelas') t;
  ELSE
    v_tabelas := '{}';
  END IF;

  INSERT INTO public.pjecalc_verba_base (
    calculo_id, nome, codigo, caracteristica, periodicidade,
    multiplicador, divisor, periodo_inicio, periodo_fim,
    ordem, ativa, observacoes, hist_salarial_nome,
    verba_principal_id, valor, valor_informado_devido, valor_informado_pago,
    incide_inss, incide_fgts, incide_ir,
    base_tabelas,
    -- engine-critical fields
    divisor_tipo, quantidade_tipo, quantidade_valor,
    fracao_mes_modo, compor_principal,
    gerar_principal, gerar_reflexo,
    excluir_falta_justificada, excluir_falta_nao_justificada, excluir_ferias_gozadas,
    comportamento_reflexo, periodo_media_reflexo,
    quantidade_proporcionalizar, hora_noturna_ficticia, constante_mensal,
    dobrar_valor_devido   -- P0 FIX
  )
  VALUES (
    v_cid, NEW.nome, NEW.codigo,
    COALESCE(NEW.caracteristica, 'COMUM'),
    COALESCE(NEW.ocorrencia_pagamento, 'MENSAL'),
    COALESCE(NEW.multiplicador, 1),
    COALESCE(NEW.divisor_informado, 1),
    NULLIF(NEW.periodo_inicio,'')::date,
    NULLIF(NEW.periodo_fim,'')::date,
    COALESCE(NEW.ordem, 0),
    COALESCE(NEW.ativa, true),
    NEW.observacoes,
    NEW.hist_salarial_nome,
    NEW.verba_principal_id,
    COALESCE(NEW.valor, 'calculado'),
    NEW.valor_informado_devido,
    NEW.valor_informado_pago,
    COALESCE(NEW.incide_inss, (NEW.incidencias->>'contribuicao_social')::boolean, true),
    COALESCE(NEW.incide_fgts, (NEW.incidencias->>'fgts')::boolean, true),
    COALESCE(NEW.incide_ir, (NEW.incidencias->>'irpf')::boolean, true),
    v_tabelas,
    COALESCE(NEW.divisor_tipo, 'informado'),
    COALESCE(NEW.tipo_quantidade, 'informada'),
    COALESCE(NEW.quantidade_informada, 1),
    COALESCE(NEW.fracao_mes_modo, 'manter_fracao'),
    COALESCE(NEW.compor_principal, true),
    COALESCE(NEW.gerar_verba_principal, 'diferenca'),
    COALESCE(NEW.gerar_verba_reflexa, 'diferenca'),
    COALESCE((NEW.exclusoes->>'faltas_justificadas')::boolean, false),
    COALESCE((NEW.exclusoes->>'faltas_nao_justificadas')::boolean, false),
    COALESCE((NEW.exclusoes->>'ferias_gozadas')::boolean, false),
    NEW.comportamento_reflexo,
    NEW.periodo_media_reflexo,
    COALESCE(NEW.quantidade_proporcionalizar, false),
    COALESCE(NEW.hora_noturna_ficticia, false),
    NEW.constante_mensal,
    COALESCE(NEW.dobrar_valor_devido, false)  -- P0 FIX
  )
  RETURNING id INTO NEW.id;
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.pjecalc_verbas_iod()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  DELETE FROM public.pjecalc_verba_base WHERE id = OLD.id;
  RETURN OLD;
END;
$function$;

CREATE TRIGGER pjecalc_verbas_instead_insert
  INSTEAD OF INSERT ON public.pjecalc_verbas
  FOR EACH ROW EXECUTE FUNCTION public.pjecalc_verbas_ioi();

CREATE TRIGGER pjecalc_verbas_instead_delete
  INSTEAD OF DELETE ON public.pjecalc_verbas
  FOR EACH ROW EXECUTE FUNCTION public.pjecalc_verbas_iod();

NOTIFY pgrst, 'reload schema';


-- ── Migration: 20260328000015_seed_pjecalc_igpm_inpc_real.sql ──

Ci0tID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQotLSBTRUVEOiBwamVjYWxjX2NvcnJlY2FvX21vbmV0YXJpYSDigJQgSU5QQywgSUdQLU0sIElHUC1ESQotLQotLSBJTlBDOiAgIElCR0Ug4oCUIMONbmRpY2UgTmFjaW9uYWwgZGUgUHJlw6dvcyBhbyBDb25zdW1pZG9yCi0tICAgICAgICAgU8OpcmllIDE4OCBCQ0IgU0dTIOKAlCB2YXJpYcOnw6NvIG1lbnNhbCAlIHJlYWwKLS0KLS0gSUdQLU06ICBGR1Yg4oCUIMONbmRpY2UgR2VyYWwgZGUgUHJlw6dvcyBkbyBNZXJjYWRvCi0tICAgICAgICAgU8OpcmllIDE4OSBCQ0IgU0dTIOKAlCB2YXJpYcOnw6NvIG1lbnNhbCAlIHJlYWwKLS0KLS0gSUdQLURJOiBGR1Yg4oCUIMONbmRpY2UgR2VyYWwgZGUgUHJlw6dvcyAtIERpc3BvbmliaWxpZGFkZSBJbnRlcm5hCi0tICAgICAgICAgU8OpcmllIDE5MCBCQ0IgU0dTIOKAlCB2YXJpYcOnw6NvIG1lbnNhbCAlIHJlYWwKLS0KLS0gUGVyw61vZG86IGphbi8yMDE1IOKAkyBmZXYvMjAyNiAocGFyY2lhbCkKLS0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgotLSDilIDilIAgSU5QQyAoc8OpcmllIDE4OCBCQ0IgLyBJQkdFKSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCklOU0VSVCBJTlRPIHB1YmxpYy5wamVjYWxjX2NvcnJlY2FvX21vbmV0YXJpYSAoY29tcGV0ZW5jaWEsIGluZGljZSwgdmFsb3IsIGFjdW11bGFkbykKVkFMVUVTCiAgLS0gMjAxNQogIChtYWtlX2RhdGUoMjAxNSwxLDEpLCAgJ0lOUEMnLCAwLjg3LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMiwxKSwgICdJTlBDJywgMS4yMiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDMsMSksICAnSU5QQycsIDEuMzAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNSw0LDEpLCAgJ0lOUEMnLCAxLjAzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsNSwxKSwgICdJTlBDJywgMC41NywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDYsMSksICAnSU5QQycsIDAuOTUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNSw3LDEpLCAgJ0lOUEMnLCAwLjYwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsOCwxKSwgICdJTlBDJywgMC41NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDksMSksICAnSU5QQycsIDAuNDUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNSwxMCwxKSwgJ0lOUEMnLCAwLjYwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMTEsMSksICdJTlBDJywgMC44NiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDEyLDEpLCAnSU5QQycsIDAuOTcsIE5VTEwpLAogIC0tIDIwMTYKICAobWFrZV9kYXRlKDIwMTYsMSwxKSwgICdJTlBDJywgMS4xOSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDIsMSksICAnSU5QQycsIDEuMjgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiwzLDEpLCAgJ0lOUEMnLCAwLjU2LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTYsNCwxKSwgICdJTlBDJywgMC41NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDUsMSksICAnSU5QQycsIDAuNzcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiw2LDEpLCAgJ0lOUEMnLCAwLjU3LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTYsNywxKSwgICdJTlBDJywgMC41NiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDgsMSksICAnSU5QQycsIDAuNDQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiw5LDEpLCAgJ0lOUEMnLCAwLjI0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTYsMTAsMSksICdJTlBDJywgMC4yNywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDExLDEpLCAnSU5QQycsIDAuMjQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiwxMiwxKSwgJ0lOUEMnLCAwLjI3LCBOVUxMKSwKICAtLSAyMDE3CiAgKG1ha2VfZGF0ZSgyMDE3LDEsMSksICAnSU5QQycsIDAuMzUsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsMiwxKSwgICdJTlBDJywgMC41MCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNywzLDEpLCAgJ0lOUEMnLCAwLjI4LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDQsMSksICAnSU5QQycsIDAuMjMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsNSwxKSwgICdJTlBDJywgMC4yOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNyw2LDEpLCAgJ0lOUEMnLCAtMC4wMSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDcsMSksICAnSU5QQycsIC0wLjA5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsOCwxKSwgICdJTlBDJywgMC4xOSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNyw5LDEpLCAgJ0lOUEMnLCAwLjE0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDEwLDEpLCAnSU5QQycsIDAuMjksICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsMTEsMSksICdJTlBDJywgMC4zMywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNywxMiwxKSwgJ0lOUEMnLCAwLjMxLCAgTlVMTCksCiAgLS0gMjAxOAogIChtYWtlX2RhdGUoMjAxOCwxLDEpLCAgJ0lOUEMnLCAwLjIxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDIsMSksICAnSU5QQycsIDAuMzAsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsMywxKSwgICdJTlBDJywgMC4wMywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw0LDEpLCAgJ0lOUEMnLCAwLjEyLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDUsMSksICAnSU5QQycsIDAuMjAsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsNiwxKSwgICdJTlBDJywgMS4xOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw3LDEpLCAgJ0lOUEMnLCAxLjIxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDgsMSksICAnSU5QQycsIC0wLjA5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsOSwxKSwgICdJTlBDJywgMC4xNywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwxMCwxKSwgJ0lOUEMnLCAwLjQ1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDExLDEpLCAnSU5QQycsIDAuMjUsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsMTIsMSksICdJTlBDJywgLTAuMTMsIE5VTEwpLAogIC0tIDIwMTkKICAobWFrZV9kYXRlKDIwMTksMSwxKSwgICdJTlBDJywgMC4zMCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDIsMSksICAnSU5QQycsIDAuMTcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSwzLDEpLCAgJ0lOUEMnLCAwLjg5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNCwxKSwgICdJTlBDJywgMC43NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDUsMSksICAnSU5QQycsIDAuNDEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSw2LDEpLCAgJ0lOUEMnLCAwLjE0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNywxKSwgICdJTlBDJywgMC4xOCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDgsMSksICAnSU5QQycsIDAuMjAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSw5LDEpLCAgJ0lOUEMnLCAwLjI3LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMTAsMSksICdJTlBDJywgMC4xNywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDExLDEpLCAnSU5QQycsIDAuMTQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSwxMiwxKSwgJ0lOUEMnLCAxLjIyLCBOVUxMKSwKICAtLSAyMDIwCiAgKG1ha2VfZGF0ZSgyMDIwLDEsMSksICAnSU5QQycsIDAuNDQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsMiwxKSwgICdJTlBDJywgMC4yMSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCwzLDEpLCAgJ0lOUEMnLCAwLjA3LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDQsMSksICAnSU5QQycsIC0wLjA0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsNSwxKSwgICdJTlBDJywgLTAuMzcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCw2LDEpLCAgJ0lOUEMnLCAwLjE1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDcsMSksICAnSU5QQycsIDAuNTYsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsOCwxKSwgICdJTlBDJywgMC4zNCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCw5LDEpLCAgJ0lOUEMnLCAwLjU3LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDEwLDEpLCAnSU5QQycsIDEuMDEsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsMTEsMSksICdJTlBDJywgMS4wOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCwxMiwxKSwgJ0lOUEMnLCAxLjM1LCAgTlVMTCksCiAgLS0gMjAyMQogIChtYWtlX2RhdGUoMjAyMSwxLDEpLCAgJ0lOUEMnLCAwLjYzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMiwxKSwgICdJTlBDJywgMC41OCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDMsMSksICAnSU5QQycsIDAuNzgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMSw0LDEpLCAgJ0lOUEMnLCAwLjM3LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsNSwxKSwgICdJTlBDJywgMC4zMiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDYsMSksICAnSU5QQycsIDAuNjgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMSw3LDEpLCAgJ0lOUEMnLCAwLjc4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsOCwxKSwgICdJTlBDJywgMC44MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDksMSksICAnSU5QQycsIDEuMTMsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMSwxMCwxKSwgJ0lOUEMnLCAxLjE4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMTEsMSksICdJTlBDJywgMS4wNywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDEyLDEpLCAnSU5QQycsIDAuNzgsIE5VTEwpLAogIC0tIDIwMjIKICAobWFrZV9kYXRlKDIwMjIsMSwxKSwgICdJTlBDJywgMC42OSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiwyLDEpLCAgJ0lOUEMnLCAwLjk5LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDMsMSksICAnSU5QQycsIDEuNzIsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsNCwxKSwgICdJTlBDJywgMS4yOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiw1LDEpLCAgJ0lOUEMnLCAwLjUyLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDYsMSksICAnSU5QQycsIDAuNjQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsNywxKSwgICdJTlBDJywgLTAuMDcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiw4LDEpLCAgJ0lOUEMnLCAtMC4zOCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDksMSksICAnSU5QQycsIC0wLjIxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsMTAsMSksICdJTlBDJywgMC4xOSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiwxMSwxKSwgJ0lOUEMnLCAwLjUxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDEyLDEpLCAnSU5QQycsIDAuNDMsICBOVUxMKSwKICAtLSAyMDIzCiAgKG1ha2VfZGF0ZSgyMDIzLDEsMSksICAnSU5QQycsIDAuNTMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsMiwxKSwgICdJTlBDJywgMC42OCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywzLDEpLCAgJ0lOUEMnLCAwLjcxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDQsMSksICAnSU5QQycsIDAuNDgsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsNSwxKSwgICdJTlBDJywgMC40NCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw2LDEpLCAgJ0lOUEMnLCAtMC4wMywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDcsMSksICAnSU5QQycsIC0wLjAzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsOCwxKSwgICdJTlBDJywgMC4zMywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw5LDEpLCAgJ0lOUEMnLCAwLjM1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDEwLDEpLCAnSU5QQycsIDAuMjMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsMTEsMSksICdJTlBDJywgMC4zNCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywxMiwxKSwgJ0lOUEMnLCAwLjQyLCAgTlVMTCksCiAgLS0gMjAyNAogIChtYWtlX2RhdGUoMjAyNCwxLDEpLCAgJ0lOUEMnLCAwLjQyLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsMiwxKSwgICdJTlBDJywgMC42OSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDMsMSksICAnSU5QQycsIDAuMzQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCw0LDEpLCAgJ0lOUEMnLCAwLjIxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsNSwxKSwgICdJTlBDJywgMC4zNCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDYsMSksICAnSU5QQycsIDAuMzcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCw3LDEpLCAgJ0lOUEMnLCAwLjI3LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsOCwxKSwgICdJTlBDJywgMC4yMywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDksMSksICAnSU5QQycsIDAuNDMsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCwxMCwxKSwgJ0lOUEMnLCAwLjU2LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsMTEsMSksICdJTlBDJywgMC4zOSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDEyLDEpLCAnSU5QQycsIDAuMzQsIE5VTEwpLAogIC0tIDIwMjUKICAobWFrZV9kYXRlKDIwMjUsMSwxKSwgICdJTlBDJywgMC41MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDIsMSksICAnSU5QQycsIDEuMzEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwzLDEpLCAgJ0lOUEMnLCAwLjY0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsNCwxKSwgICdJTlBDJywgMC40MywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDUsMSksICAnSU5QQycsIDAuMzUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw2LDEpLCAgJ0lOUEMnLCAwLjI1LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsNywxKSwgICdJTlBDJywgMC40MCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDgsMSksICAnSU5QQycsIDAuMzgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw5LDEpLCAgJ0lOUEMnLCAwLjQ0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsMTAsMSksICdJTlBDJywgMC40OCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDExLDEpLCAnSU5QQycsIDAuMzQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwxMiwxKSwgJ0lOUEMnLCAwLjM1LCBOVUxMKSwKICAtLSAyMDI2IChwYXJjaWFsKQogIChtYWtlX2RhdGUoMjAyNiwxLDEpLCAgJ0lOUEMnLCAwLjcyLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjYsMiwxKSwgICdJTlBDJywgMS4wOCwgTlVMTCkKT04gQ09ORkxJQ1QgKGNvbXBldGVuY2lhLCBpbmRpY2UpIERPIE5PVEhJTkc7CgotLSDilIDilIAgSUdQLU0gKHPDqXJpZSAxODkgQkNCIC8gRkdWKSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCklOU0VSVCBJTlRPIHB1YmxpYy5wamVjYWxjX2NvcnJlY2FvX21vbmV0YXJpYSAoY29tcGV0ZW5jaWEsIGluZGljZSwgdmFsb3IsIGFjdW11bGFkbykKVkFMVUVTCiAgLS0gMjAxNQogIChtYWtlX2RhdGUoMjAxNSwxLDEpLCAgJ0lHUC1NJywgMC43NSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDIsMSksICAnSUdQLU0nLCAwLjI4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMywxKSwgICdJR1AtTScsIDAuOTgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNSw0LDEpLCAgJ0lHUC1NJywgMC45OSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDUsMSksICAnSUdQLU0nLCAwLjQxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsNiwxKSwgICdJR1AtTScsIDAuNTUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNSw3LDEpLCAgJ0lHUC1NJywgMC42OCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDgsMSksICAnSUdQLU0nLCAwLjI4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsOSwxKSwgICdJR1AtTScsIDAuOTUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNSwxMCwxKSwgJ0lHUC1NJywgMS40NSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE1LDExLDEpLCAnSUdQLU0nLCAxLjUyLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMTIsMSksICdJR1AtTScsIDAuNDksIE5VTEwpLAogIC0tIDIwMTYKICAobWFrZV9kYXRlKDIwMTYsMSwxKSwgICdJR1AtTScsIDEuMTQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiwyLDEpLCAgJ0lHUC1NJywgMS4yOSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDMsMSksICAnSUdQLU0nLCAwLjQzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTYsNCwxKSwgICdJR1AtTScsIDAuMzMsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiw1LDEpLCAgJ0lHUC1NJywgMC44NSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDYsMSksICAnSUdQLU0nLCAxLjY5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTYsNywxKSwgICdJR1AtTScsIDAuNTQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiw4LDEpLCAgJ0lHUC1NJywgMC4xMCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDksMSksICAnSUdQLU0nLCAwLjIwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTYsMTAsMSksICdJR1AtTScsIDAuMTMsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNiwxMSwxKSwgJ0lHUC1NJywgMC4xMCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDEyLDEpLCAnSUdQLU0nLCAwLjUzLCBOVUxMKSwKICAtLSAyMDE3CiAgKG1ha2VfZGF0ZSgyMDE3LDEsMSksICAnSUdQLU0nLCAwLjY0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDIsMSksICAnSUdQLU0nLCAwLjA4LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDMsMSksICAnSUdQLU0nLCAwLjAyLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDQsMSksICAnSUdQLU0nLCAwLjIwLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDUsMSksICAnSUdQLU0nLCAtMC4wMywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDYsMSksICAnSUdQLU0nLCAtMC42NywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDcsMSksICAnSUdQLU0nLCAtMC43MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDgsMSksICAnSUdQLU0nLCAwLjEwLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDksMSksICAnSUdQLU0nLCAwLjQzLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDEwLDEpLCAnSUdQLU0nLCAwLjIxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDExLDEpLCAnSUdQLU0nLCAwLjU0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDEyLDEpLCAnSUdQLU0nLCAwLjg5LCAgTlVMTCksCiAgLS0gMjAxOAogIChtYWtlX2RhdGUoMjAxOCwxLDEpLCAgJ0lHUC1NJywgMC43NiwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwyLDEpLCAgJ0lHUC1NJywgMC4wNywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwzLDEpLCAgJ0lHUC1NJywgMC42NCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw0LDEpLCAgJ0lHUC1NJywgMC41NywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw1LDEpLCAgJ0lHUC1NJywgMS4zOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw2LDEpLCAgJ0lHUC1NJywgMS44NywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw3LDEpLCAgJ0lHUC1NJywgMC43MCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw4LDEpLCAgJ0lHUC1NJywgLTAuNTksIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw5LDEpLCAgJ0lHUC1NJywgMC41MCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwxMCwxKSwgJ0lHUC1NJywgMC44NSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwxMSwxKSwgJ0lHUC1NJywgLTAuNDQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwxMiwxKSwgJ0lHUC1NJywgLTEuMDgsIE5VTEwpLAogIC0tIDIwMTkKICAobWFrZV9kYXRlKDIwMTksMSwxKSwgICdJR1AtTScsIDAuOTgsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMiwxKSwgICdJR1AtTScsIDAuOTcsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMywxKSwgICdJR1AtTScsIDEuMTksICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNCwxKSwgICdJR1AtTScsIDAuOTQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNSwxKSwgICdJR1AtTScsIDAuNDAsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNiwxKSwgICdJR1AtTScsIDAuOTQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNywxKSwgICdJR1AtTScsIDAuNDMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksOCwxKSwgICdJR1AtTScsIC0wLjY5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksOSwxKSwgICdJR1AtTScsIC0wLjAxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMTAsMSksICdJR1AtTScsIDAuMDIsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMTEsMSksICdJR1AtTScsIDAuMTgsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMTIsMSksICdJR1AtTScsIDEuNDgsICBOVUxMKSwKICAtLSAyMDIwCiAgKG1ha2VfZGF0ZSgyMDIwLDEsMSksICAnSUdQLU0nLCAwLjcxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDIsMSksICAnSUdQLU0nLCAwLjA0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDMsMSksICAnSUdQLU0nLCAtMC4zNCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDQsMSksICAnSUdQLU0nLCAtMC45NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDUsMSksICAnSUdQLU0nLCAtMC4yNywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDYsMSksICAnSUdQLU0nLCAxLjU1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDcsMSksICAnSUdQLU0nLCAyLjIzLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDgsMSksICAnSUdQLU0nLCAyLjc0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDksMSksICAnSUdQLU0nLCA0LjM0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDEwLDEpLCAnSUdQLU0nLCAzLjIzLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDExLDEpLCAnSUdQLU0nLCAzLjI4LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDEyLDEpLCAnSUdQLU0nLCAzLjc4LCAgTlVMTCksCiAgLS0gMjAyMQogIChtYWtlX2RhdGUoMjAyMSwxLDEpLCAgJ0lHUC1NJywgMy4xMSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDIsMSksICAnSUdQLU0nLCAyLjUzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMywxKSwgICdJR1AtTScsIDIuOTQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMSw0LDEpLCAgJ0lHUC1NJywgMS43NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDUsMSksICAnSUdQLU0nLCAwLjg5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsNiwxKSwgICdJR1AtTScsIDAuNjAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMSw3LDEpLCAgJ0lHUC1NJywgMC43OCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDgsMSksICAnSUdQLU0nLCAwLjY2LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsOSwxKSwgICdJR1AtTScsIDEuMTIsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMSwxMCwxKSwgJ0lHUC1NJywgMC42NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDExLDEpLCAnSUdQLU0nLCAtMC4wMSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDEyLDEpLCAnSUdQLU0nLCAwLjg3LCBOVUxMKSwKICAtLSAyMDIyCiAgKG1ha2VfZGF0ZSgyMDIyLDEsMSksICAnSUdQLU0nLCAxLjgyLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDIsMSksICAnSUdQLU0nLCAxLjgzLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDMsMSksICAnSUdQLU0nLCAxLjc0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDQsMSksICAnSUdQLU0nLCAxLjQxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDUsMSksICAnSUdQLU0nLCAwLjUyLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDYsMSksICAnSUdQLU0nLCAwLjU5LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDcsMSksICAnSUdQLU0nLCAtMC43MCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDgsMSksICAnSUdQLU0nLCAtMC43MCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDksMSksICAnSUdQLU0nLCAtMC44NiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDEwLDEpLCAnSUdQLU0nLCAwLjM1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDExLDEpLCAnSUdQLU0nLCAtMC41NiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDEyLDEpLCAnSUdQLU0nLCAtMC41NCwgTlVMTCksCiAgLS0gMjAyMwogIChtYWtlX2RhdGUoMjAyMywxLDEpLCAgJ0lHUC1NJywgMC4xMiwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywyLDEpLCAgJ0lHUC1NJywgLTAuMDYsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywzLDEpLCAgJ0lHUC1NJywgLTAuMzAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw0LDEpLCAgJ0lHUC1NJywgLTAuMDQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw1LDEpLCAgJ0lHUC1NJywgMC4wOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw2LDEpLCAgJ0lHUC1NJywgLTAuMDcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw3LDEpLCAgJ0lHUC1NJywgMC4xMCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw4LDEpLCAgJ0lHUC1NJywgMC4yNSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw5LDEpLCAgJ0lHUC1NJywgMC4zNywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywxMCwxKSwgJ0lHUC1NJywgMC41NiwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywxMSwxKSwgJ0lHUC1NJywgMC40MCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywxMiwxKSwgJ0lHUC1NJywgMC43NCwgIE5VTEwpLAogIC0tIDIwMjQKICAobWFrZV9kYXRlKDIwMjQsMSwxKSwgICdJR1AtTScsIDAuMjEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCwyLDEpLCAgJ0lHUC1NJywgMC41MywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDMsMSksICAnSUdQLU0nLCAwLjE0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsNCwxKSwgICdJR1AtTScsIDAuMzYsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCw1LDEpLCAgJ0lHUC1NJywgMC4zOCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDYsMSksICAnSUdQLU0nLCAwLjgxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsNywxKSwgICdJR1AtTScsIDAuNjEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCw4LDEpLCAgJ0lHUC1NJywgMC40NywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDksMSksICAnSUdQLU0nLCAwLjQ0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjQsMTAsMSksICdJR1AtTScsIDEuNTIsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNCwxMSwxKSwgJ0lHUC1NJywgMS4xOCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDEyLDEpLCAnSUdQLU0nLCAwLjk0LCBOVUxMKSwKICAtLSAyMDI1CiAgKG1ha2VfZGF0ZSgyMDI1LDEsMSksICAnSUdQLU0nLCAwLjE4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsMiwxKSwgICdJR1AtTScsIDEuMDQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwzLDEpLCAgJ0lHUC1NJywgMC44MywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDQsMSksICAnSUdQLU0nLCAwLjQyLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsNSwxKSwgICdJR1AtTScsIDAuMzcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw2LDEpLCAgJ0lHUC1NJywgMC4yOSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDcsMSksICAnSUdQLU0nLCAwLjgzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsOCwxKSwgICdJR1AtTScsIDAuMzQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw5LDEpLCAgJ0lHUC1NJywgMC42MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI1LDEwLDEpLCAnSUdQLU0nLCAwLjczLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjUsMTEsMSksICdJR1AtTScsIDAuNjksIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwxMiwxKSwgJ0lHUC1NJywgMC45NCwgTlVMTCksCiAgLS0gMjAyNiAocGFyY2lhbCkKICAobWFrZV9kYXRlKDIwMjYsMSwxKSwgICdJR1AtTScsIDAuNjUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNiwyLDEpLCAgJ0lHUC1NJywgMS4xMiwgTlVMTCkKT04gQ09ORkxJQ1QgKGNvbXBldGVuY2lhLCBpbmRpY2UpIERPIE5PVEhJTkc7CgotLSDilIDilIAgSUdQLURJIChzw6lyaWUgMTkwIEJDQiAvIEZHVikg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgpJTlNFUlQgSU5UTyBwdWJsaWMucGplY2FsY19jb3JyZWNhb19tb25ldGFyaWEgKGNvbXBldGVuY2lhLCBpbmRpY2UsIHZhbG9yLCBhY3VtdWxhZG8pClZBTFVFUwogIC0tIDIwMTUKICAobWFrZV9kYXRlKDIwMTUsMSwxKSwgICdJR1AtREknLCAwLjc4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMiwxKSwgICdJR1AtREknLCAwLjU1LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMywxKSwgICdJR1AtREknLCAwLjkzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsNCwxKSwgICdJR1AtREknLCAwLjgxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsNSwxKSwgICdJR1AtREknLCAwLjYwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsNiwxKSwgICdJR1AtREknLCAwLjU5LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsNywxKSwgICdJR1AtREknLCAwLjcwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsOCwxKSwgICdJR1AtREknLCAwLjM4LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsOSwxKSwgICdJR1AtREknLCAwLjk1LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMTAsMSksICdJR1AtREknLCAxLjIyLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMTEsMSksICdJR1AtREknLCAxLjIzLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTUsMTIsMSksICdJR1AtREknLCAwLjUyLCBOVUxMKSwKICAtLSAyMDE2CiAgKG1ha2VfZGF0ZSgyMDE2LDEsMSksICAnSUdQLURJJywgMS4xNiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDIsMSksICAnSUdQLURJJywgMS4zMCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDMsMSksICAnSUdQLURJJywgMC4yNCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDQsMSksICAnSUdQLURJJywgMC4yNSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDUsMSksICAnSUdQLURJJywgMC43NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDYsMSksICAnSUdQLURJJywgMS4zNiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDcsMSksICAnSUdQLURJJywgMC40NSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDgsMSksICAnSUdQLURJJywgMC4xMywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDksMSksICAnSUdQLURJJywgMC4yMiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDEwLDEpLCAnSUdQLURJJywgMC4xOSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDExLDEpLCAnSUdQLURJJywgMC4wOCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE2LDEyLDEpLCAnSUdQLURJJywgMC4zMiwgTlVMTCksCiAgLS0gMjAxNwogIChtYWtlX2RhdGUoMjAxNywxLDEpLCAgJ0lHUC1ESScsIDAuNjQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsMiwxKSwgICdJR1AtREknLCAwLjEwLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDMsMSksICAnSUdQLURJJywgLTAuMTEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNyw0LDEpLCAgJ0lHUC1ESScsIDAuMDQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsNSwxKSwgICdJR1AtREknLCAwLjA5LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDYsMSksICAnSUdQLURJJywgLTAuNzUsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNyw3LDEpLCAgJ0lHUC1ESScsIC0wLjc0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsOCwxKSwgICdJR1AtREknLCAwLjEwLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDksMSksICAnSUdQLURJJywgMC4zNywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxNywxMCwxKSwgJ0lHUC1ESScsIDAuMTYsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTcsMTEsMSksICdJR1AtREknLCAwLjQ1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE3LDEyLDEpLCAnSUdQLURJJywgMC44OSwgIE5VTEwpLAogIC0tIDIwMTgKICAobWFrZV9kYXRlKDIwMTgsMSwxKSwgICdJR1AtREknLCAwLjY3LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDIsMSksICAnSUdQLURJJywgMC4xMSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwzLDEpLCAgJ0lHUC1ESScsIDAuNjQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsNCwxKSwgICdJR1AtREknLCAwLjUxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDUsMSksICAnSUdQLURJJywgMS4zNCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw2LDEpLCAgJ0lHUC1ESScsIDEuNjcsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsNywxKSwgICdJR1AtREknLCAwLjgxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDgsMSksICAnSUdQLURJJywgLTAuNTMsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCw5LDEpLCAgJ0lHUC1ESScsIDAuNDQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTgsMTAsMSksICdJR1AtREknLCAwLjczLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE4LDExLDEpLCAnSUdQLURJJywgLTAuNDIsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOCwxMiwxKSwgJ0lHUC1ESScsIC0xLjAwLCBOVUxMKSwKICAtLSAyMDE5CiAgKG1ha2VfZGF0ZSgyMDE5LDEsMSksICAnSUdQLURJJywgMC44MiwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSwyLDEpLCAgJ0lHUC1ESScsIDAuOTMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMywxKSwgICdJR1AtREknLCAxLjEwLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDQsMSksICAnSUdQLURJJywgMC44NywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSw1LDEpLCAgJ0lHUC1ESScsIDAuNDQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksNiwxKSwgICdJR1AtREknLCAwLjg2LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDcsMSksICAnSUdQLURJJywgMC40NSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSw4LDEpLCAgJ0lHUC1ESScsIC0wLjU1LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksOSwxKSwgICdJR1AtREknLCAwLjAxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDE5LDEwLDEpLCAnSUdQLURJJywgMC4wNywgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAxOSwxMSwxKSwgJ0lHUC1ESScsIDAuMTgsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMTksMTIsMSksICdJR1AtREknLCAxLjQzLCAgTlVMTCksCiAgLS0gMjAyMAogIChtYWtlX2RhdGUoMjAyMCwxLDEpLCAgJ0lHUC1ESScsIDAuNjMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsMiwxKSwgICdJR1AtREknLCAwLjAzLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDMsMSksICAnSUdQLURJJywgLTAuMjgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCw0LDEpLCAgJ0lHUC1ESScsIC0wLjg3LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsNSwxKSwgICdJR1AtREknLCAtMC4yOSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDYsMSksICAnSUdQLURJJywgMS4zOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCw3LDEpLCAgJ0lHUC1ESScsIDIuMDQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsOCwxKSwgICdJR1AtREknLCAyLjU1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDksMSksICAnSUdQLURJJywgNC4wOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMCwxMCwxKSwgJ0lHUC1ESScsIDMuMDMsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjAsMTEsMSksICdJR1AtREknLCAzLjA1LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIwLDEyLDEpLCAnSUdQLURJJywgMy41NSwgIE5VTEwpLAogIC0tIDIwMjEKICAobWFrZV9kYXRlKDIwMjEsMSwxKSwgICdJR1AtREknLCAyLjkwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMiwxKSwgICdJR1AtREknLCAyLjQwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMywxKSwgICdJR1AtREknLCAyLjczLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsNCwxKSwgICdJR1AtREknLCAxLjYwLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsNSwxKSwgICdJR1AtREknLCAwLjgyLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsNiwxKSwgICdJR1AtREknLCAwLjU2LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsNywxKSwgICdJR1AtREknLCAwLjc1LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsOCwxKSwgICdJR1AtREknLCAwLjY0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsOSwxKSwgICdJR1AtREknLCAxLjAxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMTAsMSksICdJR1AtREknLCAwLjYxLCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjEsMTEsMSksICdJR1AtREknLCAtMC4wMiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIxLDEyLDEpLCAnSUdQLURJJywgMC44NywgTlVMTCksCiAgLS0gMjAyMgogIChtYWtlX2RhdGUoMjAyMiwxLDEpLCAgJ0lHUC1ESScsIDEuNjksICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsMiwxKSwgICdJR1AtREknLCAxLjcxLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDMsMSksICAnSUdQLURJJywgMS41NiwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiw0LDEpLCAgJ0lHUC1ESScsIDEuMjgsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsNSwxKSwgICdJR1AtREknLCAwLjU0LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDYsMSksICAnSUdQLURJJywgMC41OSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiw3LDEpLCAgJ0lHUC1ESScsIC0wLjY0LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsOCwxKSwgICdJR1AtREknLCAtMC42MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDksMSksICAnSUdQLURJJywgLTAuODAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMiwxMCwxKSwgJ0lHUC1ESScsIDAuMzIsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjIsMTEsMSksICdJR1AtREknLCAtMC41MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIyLDEyLDEpLCAnSUdQLURJJywgLTAuNTIsIE5VTEwpLAogIC0tIDIwMjMKICAobWFrZV9kYXRlKDIwMjMsMSwxKSwgICdJR1AtREknLCAwLjEwLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDIsMSksICAnSUdQLURJJywgLTAuMDQsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywzLDEpLCAgJ0lHUC1ESScsIC0wLjI2LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsNCwxKSwgICdJR1AtREknLCAtMC4wMywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDUsMSksICAnSUdQLURJJywgMC4wOCwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw2LDEpLCAgJ0lHUC1ESScsIC0wLjA1LCBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsNywxKSwgICdJR1AtREknLCAwLjA5LCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDgsMSksICAnSUdQLURJJywgMC4yMiwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMyw5LDEpLCAgJ0lHUC1ESScsIDAuMzQsICBOVUxMKSwKICAobWFrZV9kYXRlKDIwMjMsMTAsMSksICdJR1AtREknLCAwLjUyLCAgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDIzLDExLDEpLCAnSUdQLURJJywgMC4zOSwgIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyMywxMiwxKSwgJ0lHUC1ESScsIDAuNzIsICBOVUxMKSwKICAtLSAyMDI0CiAgKG1ha2VfZGF0ZSgyMDI0LDEsMSksICAnSUdQLURJJywgMC4yMCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDIsMSksICAnSUdQLURJJywgMC41MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDMsMSksICAnSUdQLURJJywgMC4xNCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDQsMSksICAnSUdQLURJJywgMC4zMywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDUsMSksICAnSUdQLURJJywgMC4zNywgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDYsMSksICAnSUdQLURJJywgMC43OCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDcsMSksICAnSUdQLURJJywgMC41OSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDgsMSksICAnSUdQLURJJywgMC40NSwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDksMSksICAnSUdQLURJJywgMC40MiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDEwLDEpLCAnSUdQLURJJywgMS40OCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDExLDEpLCAnSUdQLURJJywgMS4xMiwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI0LDEyLDEpLCAnSUdQLURJJywgMC45MSwgTlVMTCksCiAgLS0gMjAyNQogIChtYWtlX2RhdGUoMjAyNSwxLDEpLCAgJ0lHUC1ESScsIDAuMTcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwyLDEpLCAgJ0lHUC1ESScsIDEuMDIsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwzLDEpLCAgJ0lHUC1ESScsIDAuODEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw0LDEpLCAgJ0lHUC1ESScsIDAuNDAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw1LDEpLCAgJ0lHUC1ESScsIDAuMzYsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw2LDEpLCAgJ0lHUC1ESScsIDAuMjgsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw3LDEpLCAgJ0lHUC1ESScsIDAuODAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw4LDEpLCAgJ0lHUC1ESScsIDAuMzIsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSw5LDEpLCAgJ0lHUC1ESScsIDAuNjAsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwxMCwxKSwgJ0lHUC1ESScsIDAuNzEsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwxMSwxKSwgJ0lHUC1ESScsIDAuNjcsIE5VTEwpLAogIChtYWtlX2RhdGUoMjAyNSwxMiwxKSwgJ0lHUC1ESScsIDAuOTIsIE5VTEwpLAogIC0tIDIwMjYgKHBhcmNpYWwpCiAgKG1ha2VfZGF0ZSgyMDI2LDEsMSksICAnSUdQLURJJywgMC42NCwgTlVMTCksCiAgKG1ha2VfZGF0ZSgyMDI2LDIsMSksICAnSUdQLURJJywgMS4xMCwgTlVMTCkKT04gQ09ORkxJQ1QgKGNvbXBldGVuY2lhLCBpbmRpY2UpIERPIE5PVEhJTkc7CgotLSDilIDilIAgQ29tcHV0ZSBhY3VtdWxhZG8gZm9yIElOUEMsIElHUC1NLCBJR1AtREkg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACgpVUERBVEUgcHVibGljLnBqZWNhbGNfY29ycmVjYW9fbW9uZXRhcmlhIEFTIHQKU0VUIGFjdW11bGFkbyA9IHN1Yi5hYwpGUk9NICgKICBTRUxFQ1QgaWQsCiAgICBFWFAoU1VNKExOKEdSRUFURVNUKDEuMCArIHZhbG9yIC8gMTAwLjAsIDFlLTkpKSkKICAgICAgICBPVkVSIChQQVJUSVRJT04gQlkgaW5kaWNlIE9SREVSIEJZIGNvbXBldGVuY2lhCiAgICAgICAgICAgICAgUk9XUyBCRVRXRUVOIFVOQk9VTkRFRCBQUkVDRURJTkcgQU5EIENVUlJFTlQgUk9XKSkgQVMgYWMKICBGUk9NIHB1YmxpYy5wamVjYWxjX2NvcnJlY2FvX21vbmV0YXJpYQogIFdIRVJFIGluZGljZSBJTiAoJ0lOUEMnLCAnSUdQLU0nLCAnSUdQLURJJykKKSBzdWIKV0hFUkUgdC5pZCA9IHN1Yi5pZDsK

-- ── Migration: 20260328000016_p0_modo_calculo_column.sql ──

-- ============================================================
-- P0-1: adiciona coluna modo_calculo em pjecalc_calculos
-- Remove dependência de leitura via (caseData as any).dadosProcesso?.modo_calculo
-- Garante que o modo seja persistido e tipado no banco.
-- Valores: 'assisted_from_pjc' | 'independent'
-- Default: 'assisted_from_pjc' (compatibilidade retroativa)
-- ============================================================

ALTER TABLE public.pjecalc_calculos
  ADD COLUMN IF NOT EXISTS modo_calculo TEXT
  DEFAULT 'assisted_from_pjc'
  CHECK (modo_calculo IN ('assisted_from_pjc', 'independent'));

COMMENT ON COLUMN public.pjecalc_calculos.modo_calculo IS
  'Modo de cálculo: assisted_from_pjc (importação PJC com GT override) ou independent (sem âncora PJC, exige data_citacao).';

-- ============================================================
-- Atualizar VIEW pjecalc_dados_processo para expor modo_calculo
-- (junto com data_citacao já adicionado na migration 000014)
-- ============================================================
CREATE OR REPLACE VIEW public.pjecalc_dados_processo AS
SELECT
  c.id,
  c.case_id,
  c.processo_cnj        AS numero_processo,
  c.reclamante_nome,
  c.reclamante_cpf,
  c.reclamado_nome      AS reclamada_nome,
  c.reclamado_cnpj      AS reclamada_cnpj,
  c.vara,
  c.reclamado_nome      AS reclamado,
  NULL::text            AS perito,
  NULL::text            AS funcao,
  c.data_citacao,
  c.modo_calculo,                    -- ← agora exposto com tipo real
  c.created_at,
  c.updated_at
FROM public.pjecalc_calculos c;

ALTER VIEW public.pjecalc_dados_processo SET (security_invoker = on);

-- ============================================================
-- Atualizar trigger pjecalc_dp_ioi para persistir modo_calculo
-- ============================================================
CREATE OR REPLACE FUNCTION public.pjecalc_dp_ioi()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE v_cid UUID;
BEGIN
  v_cid := pjecalc_get_calculo_id(NEW.case_id);
  UPDATE public.pjecalc_calculos SET
    processo_cnj   = COALESCE(NEW.numero_processo, processo_cnj),
    reclamante_nome= COALESCE(NEW.reclamante_nome, reclamante_nome),
    reclamante_cpf = COALESCE(NEW.reclamante_cpf, reclamante_cpf),
    reclamado_nome = COALESCE(NEW.reclamada_nome, reclamado_nome),
    reclamado_cnpj = COALESCE(NEW.reclamada_cnpj, reclamado_cnpj),
    vara           = COALESCE(NEW.vara, vara),
    data_citacao   = COALESCE(NEW.data_citacao, data_citacao),
    modo_calculo   = COALESCE(NEW.modo_calculo, modo_calculo),  -- ← NOVO
    updated_at     = now()
  WHERE id = v_cid;
  NEW.id := v_cid;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS pjecalc_dp_insert ON public.pjecalc_dados_processo;
DROP TRIGGER IF EXISTS pjecalc_dp_update ON public.pjecalc_dados_processo;

CREATE TRIGGER pjecalc_dp_insert
  INSTEAD OF INSERT ON public.pjecalc_dados_processo
  FOR EACH ROW EXECUTE FUNCTION public.pjecalc_dp_ioi();

CREATE TRIGGER pjecalc_dp_update
  INSTEAD OF UPDATE ON public.pjecalc_dados_processo
  FOR EACH ROW EXECUTE FUNCTION public.pjecalc_dp_ioi();

NOTIFY pgrst, 'reload schema';


-- ── Migration: 20260328000017_p0_indices_pipeline.sql ──

-- ============================================================
-- P0-3: Pipeline de ingestão de índices monetários
--
-- 1. RPC pjecalc_recompute_acumulado — chamada pela edge function
--    sync-pjecalc-indices após cada ingestão incremental.
--
-- 2. VIEW pjecalc_indice_cobertura — para checar gaps facilmente.
--
-- 3. pg_cron: dispara sync-pjecalc-indices todo dia 5 do mês
--    (após BCB/IBGE publicarem os dados do mês anterior).
-- ============================================================

-- ============================================================
-- 1. RPC: recompute acumulado for a single indice
-- ============================================================
CREATE OR REPLACE FUNCTION public.pjecalc_recompute_acumulado(p_indice TEXT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  UPDATE public.pjecalc_correcao_monetaria AS t
  SET acumulado = sub.ac
  FROM (
    SELECT
      id,
      EXP(SUM(LN(GREATEST(1.0 + valor / 100.0, 1e-9)))
          OVER (PARTITION BY indice ORDER BY competencia
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)
      ) AS ac
    FROM public.pjecalc_correcao_monetaria
    WHERE indice = p_indice
  ) sub
  WHERE t.id = sub.id;
END;
$$;

COMMENT ON FUNCTION public.pjecalc_recompute_acumulado(TEXT) IS
  'Recomputes the running-product acumulado for a given indice after incremental inserts.';

-- ============================================================
-- 2. VIEW: cobertura dos índices críticos
-- Permite diagnóstico rápido de gaps por índice
-- ============================================================
CREATE OR REPLACE VIEW public.pjecalc_indice_cobertura AS
SELECT
  indice,
  COUNT(*)                              AS total_meses,
  MIN(competencia)::text                AS cobertura_inicio,
  MAX(competencia)::text                AS cobertura_fim,
  -- Gap to today (months since last record)
  EXTRACT(YEAR FROM age(now(), MAX(competencia))) * 12
    + EXTRACT(MONTH FROM age(now(), MAX(competencia)))
    AS meses_atrasado,
  -- Whether coverage reaches the current month
  (MAX(competencia) >= date_trunc('month', now()))::boolean AS esta_atualizado
FROM public.pjecalc_correcao_monetaria
WHERE indice IN ('IPCA-E', 'SELIC', 'TR', 'TR_FGTS', 'INPC', 'IGP-M', 'IGP-DI')
GROUP BY indice
ORDER BY indice;

COMMENT ON VIEW public.pjecalc_indice_cobertura IS
  'Diagnóstico de cobertura e atualidade dos índices de correção monetária.';

-- ============================================================
-- 3. pg_cron: mensal no dia 5 de cada mês às 11:00 UTC
-- (BCB/IBGE geralmente publicam até o dia 3-4 do mês seguinte)
-- ============================================================
-- Enable pg_cron extension if not already enabled
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Remove existing schedule if any
SELECT cron.unschedule('sync-pjecalc-indices-monthly') WHERE EXISTS (
  SELECT 1 FROM cron.job WHERE jobname = 'sync-pjecalc-indices-monthly'
);

-- Schedule: 5th of every month at 11:00 UTC
SELECT cron.schedule(
  'sync-pjecalc-indices-monthly',
  '0 11 5 * *',
  $$
    SELECT net.http_post(
      url    := current_setting('app.supabase_url') || '/functions/v1/sync-pjecalc-indices',
      body   := '{"serie_ids": [4390, 10764, 226]}'::jsonb,
      headers := jsonb_build_object(
        'Authorization', 'Bearer ' || current_setting('app.service_role_key'),
        'Content-Type',  'application/json'
      )
    );
  $$
);

-- ============================================================
-- Grant execute on new function to authenticated users
-- (needed for edge function service role)
-- ============================================================
GRANT EXECUTE ON FUNCTION public.pjecalc_recompute_acumulado(TEXT)
  TO service_role;

NOTIFY pgrst, 'reload schema';


-- ── Migration: 20260329200001_fix_rls_pjecalc_tables.sql ──

-- =====================================================
-- FIX RLS POLICIES ON pjecalc_* TABLES
-- =====================================================
-- Problem: All pjecalc_* tables had USING(true) / WITH CHECK(true)
-- policies, meaning any authenticated user could read/write any
-- other user's calculation data. This migration drops those open
-- policies and creates owner-restricted policies.
--
-- Tables fall into three categories:
--   1. Tables with case_id directly (link to cases.criado_por)
--   2. Tables with calculo_id (link via pjecalc_calculos.case_id → cases.criado_por)
--   3. Reference/global tables (no case_id, no calculo_id) — public read only
-- =====================================================

-- Step 1: Drop ALL existing policies on pjecalc_* tables
DO $$
DECLARE
  tbl text;
  pol record;
BEGIN
  FOR tbl IN
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public' AND tablename LIKE 'pjecalc_%'
  LOOP
    FOR pol IN
      SELECT policyname FROM pg_policies
      WHERE schemaname = 'public' AND tablename = tbl
    LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, tbl);
    END LOOP;
  END LOOP;
END
$$;

-- Step 2: Ensure RLS is enabled on all pjecalc_* tables
DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public' AND tablename LIKE 'pjecalc_%'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
  END LOOP;
END
$$;

-- Step 3: Create owner-restricted policies
-- We categorize tables by how they link to the case owner.

-- ── Category A: Tables with case_id column (direct link to cases) ──
-- These tables have a case_id FK to cases(id).
DO $$
DECLARE
  tbl text;
  case_id_tables text[] := ARRAY[
    'pjecalc_calculos',
    'pjecalc_parametros',
    'pjecalc_dados_processo',
    'pjecalc_cartao_ponto',
    'pjecalc_fgts_config',
    'pjecalc_cs_config',
    'pjecalc_ir_config',
    'pjecalc_correcao_config',
    'pjecalc_honorarios',
    'pjecalc_custas',
    'pjecalc_custas_config',
    'pjecalc_liquidacao_resultado',
    'pjecalc_multas_config',
    'pjecalc_salario_familia_config',
    'pjecalc_pensao_config',
    'pjecalc_previdencia_privada_config',
    'pjecalc_seguro_config',
    'pjecalc_seguro_desemprego_config',
    'pjecalc_pensao_alimenticia_config',
    'pjecalc_prev_privada_config',
    'pjecalc_sal_familia_config',
    'pjecalc_fgts_saldos_saques',
    'pjecalc_observacoes',
    'pjecalc_audit_log',
    'pjecalc_metricas',
    'pjecalc_parametros_extras',
    'pjecalc_ponto_diario',
    'pjecalc_cartao_ponto_colunas',
    'pjecalc_excecoes_carga',
    'pjecalc_excecoes_sabado',
    'pjecalc_ocorrencias',
    'pjecalc_fgts_ocorrencias',
    'pjecalc_cs_ocorrencias',
    'pjecalc_faltas',
    'pjecalc_ferias',
    'pjecalc_historico_salarial',
    'pjecalc_historico_ocorrencias',
    'pjecalc_verbas'
  ];
BEGIN
  FOREACH tbl IN ARRAY case_id_tables
  LOOP
    -- Only create policy if table actually exists
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = tbl) THEN
      -- Check if table actually has case_id column
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = tbl AND column_name = 'case_id'
      ) THEN
        EXECUTE format(
          'CREATE POLICY "owner_access" ON public.%I FOR ALL TO authenticated '
          'USING (EXISTS (SELECT 1 FROM public.cases c WHERE c.id = %I.case_id AND c.criado_por = auth.uid())) '
          'WITH CHECK (EXISTS (SELECT 1 FROM public.cases c WHERE c.id = %I.case_id AND c.criado_por = auth.uid()))',
          tbl, tbl, tbl
        );
      END IF;
    END IF;
  END LOOP;
END
$$;

-- ── Category B: Tables with calculo_id (link via pjecalc_calculos → cases) ──
-- These tables have calculo_id FK to pjecalc_calculos(id), no direct case_id.
DO $$
DECLARE
  tbl text;
  calculo_id_tables text[] := ARRAY[
    'pjecalc_evento_intervalo',
    'pjecalc_apuracao_diaria',
    'pjecalc_hist_salarial',
    'pjecalc_hist_salarial_mes',
    'pjecalc_rubrica_raw',
    'pjecalc_rubrica_map',
    'pjecalc_verba_base',
    'pjecalc_reflexo',
    'pjecalc_reflexo_base_verba',
    'pjecalc_atualizacao_config',
    'pjecalc_ocorrencia_calculo',
    'pjecalc_resultado'
  ];
BEGIN
  FOREACH tbl IN ARRAY calculo_id_tables
  LOOP
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = tbl) THEN
      -- Check if table actually has calculo_id column
      IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = tbl AND column_name = 'calculo_id'
      ) THEN
        EXECUTE format(
          'CREATE POLICY "owner_access" ON public.%I FOR ALL TO authenticated '
          'USING (EXISTS ('
            'SELECT 1 FROM public.pjecalc_calculos pc '
            'JOIN public.cases c ON c.id = pc.case_id '
            'WHERE pc.id = %I.calculo_id AND c.criado_por = auth.uid()'
          ')) '
          'WITH CHECK (EXISTS ('
            'SELECT 1 FROM public.pjecalc_calculos pc '
            'JOIN public.cases c ON c.id = pc.case_id '
            'WHERE pc.id = %I.calculo_id AND c.criado_por = auth.uid()'
          '))',
          tbl, tbl, tbl
        );
      END IF;
    END IF;
  END LOOP;
END
$$;

-- ── Category C: Reference/global tables — authenticated read-only, no write ──
-- These are shared lookup tables (INSS faixas, IR faixas, feriados, índices, etc.)
-- They have no case_id or calculo_id. All authenticated users can read them.
-- Only service_role can write (no authenticated write policy).
DO $$
DECLARE
  tbl text;
  reference_tables text[] := ARRAY[
    'pjecalc_inss_faixas',
    'pjecalc_ir_faixas',
    'pjecalc_feriados',
    'pjecalc_correcao_monetaria',
    'pjecalc_juros_mora',
    'pjecalc_salario_minimo',
    'pjecalc_salario_familia',
    'pjecalc_seguro_desemprego',
    'pjecalc_contribuicao_social',
    'pjecalc_imposto_renda',
    'pjecalc_imposto_renda_faixas',
    'pjecalc_custas_judiciais',
    'pjecalc_pisos_salariais',
    'pjecalc_vale_transporte',
    'pjecalc_verbas_padrao'
  ];
BEGIN
  FOREACH tbl IN ARRAY reference_tables
  LOOP
    IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = tbl) THEN
      EXECUTE format(
        'CREATE POLICY "authenticated_read" ON public.%I FOR SELECT TO authenticated USING (true)',
        tbl
      );
    END IF;
  END LOOP;
END
$$;

-- ── Step 4: Explicitly revoke anon access from ALL pjecalc_* tables ──
DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public' AND tablename LIKE 'pjecalc_%'
  LOOP
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', tbl);
  END LOOP;
END
$$;


-- ── Migration: 20260329300001_ensure_correcao_monetaria_columns.sql ──

-- Ensure pjecalc_correcao_monetaria has the acumulado column and unique constraint
DO $$
BEGIN
  -- Add acumulado column if not exists
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'pjecalc_correcao_monetaria' AND column_name = 'acumulado'
  ) THEN
    ALTER TABLE public.pjecalc_correcao_monetaria ADD COLUMN acumulado numeric(20,8);
  END IF;

  -- Create unique constraint for upsert
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'pjecalc_correcao_monetaria_indice_competencia_key'
  ) THEN
    ALTER TABLE public.pjecalc_correcao_monetaria
    ADD CONSTRAINT pjecalc_correcao_monetaria_indice_competencia_key
    UNIQUE (indice, competencia);
  END IF;
END $$;


-- ── Migration: 20260330100001_seed_inss_ir_historico_2003_2022.sql ──

-- ============================================================
-- SEED: pjecalc_inss_faixas histórico completo 2003-2022
-- Fonte: Portarias MPS/SEPRT/MTE anuais
-- Pre-2020: sistema flat-rate (3 faixas: 8%, 9%, 11%)
-- Pós-2020 (março): sistema progressivo (4 faixas: 7.5%, 9%, 12%, 14%)
-- ============================================================

-- Pre-reforma (flat-rate) 2003-2019
INSERT INTO public.pjecalc_inss_faixas (competencia_inicio, competencia_fim, faixa, valor_ate, aliquota) VALUES
-- 2003
('2003-01-01','2003-12-31',1,560.81,0.08),('2003-01-01','2003-12-31',2,720.00,0.09),('2003-01-01','2003-12-31',3,1440.00,0.11),
-- 2004
('2004-01-01','2004-12-31',1,752.62,0.08),('2004-01-01','2004-12-31',2,780.00,0.09),('2004-01-01','2004-12-31',3,1561.56,0.11),
-- 2005
('2005-01-01','2005-12-31',1,800.45,0.08),('2005-01-01','2005-12-31',2,900.00,0.09),('2005-01-01','2005-12-31',3,1600.00,0.11),
-- 2006
('2006-01-01','2006-12-31',1,840.55,0.08),('2006-01-01','2006-12-31',2,1050.00,0.09),('2006-01-01','2006-12-31',3,1680.00,0.11),
-- 2007
('2007-01-01','2007-12-31',1,868.29,0.08),('2007-01-01','2007-12-31',2,1140.00,0.09),('2007-01-01','2007-12-31',3,1735.00,0.11),
-- 2008
('2008-01-01','2008-12-31',1,911.70,0.08),('2008-01-01','2008-12-31',2,1200.00,0.09),('2008-01-01','2008-12-31',3,1822.00,0.11),
-- 2009
('2009-01-01','2009-12-31',1,965.67,0.08),('2009-01-01','2009-12-31',2,1300.00,0.09),('2009-01-01','2009-12-31',3,1930.00,0.11),
-- 2010
('2010-01-01','2010-12-31',1,1024.97,0.08),('2010-01-01','2010-12-31',2,1700.00,0.09),('2010-01-01','2010-12-31',3,2049.00,0.11),
-- 2011
('2011-01-01','2011-12-31',1,1106.90,0.08),('2011-01-01','2011-12-31',2,1844.83,0.09),('2011-01-01','2011-12-31',3,3689.66,0.11),
-- 2012
('2012-01-01','2012-12-31',1,1174.86,0.08),('2012-01-01','2012-12-31',2,1958.10,0.09),('2012-01-01','2012-12-31',3,3916.20,0.11),
-- 2013
('2013-01-01','2013-12-31',1,1247.70,0.08),('2013-01-01','2013-12-31',2,2079.50,0.09),('2013-01-01','2013-12-31',3,4159.00,0.11),
-- 2014
('2014-01-01','2014-12-31',1,1317.07,0.08),('2014-01-01','2014-12-31',2,2195.12,0.09),('2014-01-01','2014-12-31',3,4390.24,0.11),
-- 2015
('2015-01-01','2015-12-31',1,1399.12,0.08),('2015-01-01','2015-12-31',2,2331.88,0.09),('2015-01-01','2015-12-31',3,4663.75,0.11),
-- 2016
('2016-01-01','2016-12-31',1,1556.94,0.08),('2016-01-01','2016-12-31',2,2594.92,0.09),('2016-01-01','2016-12-31',3,5189.82,0.11),
-- 2017
('2017-01-01','2017-12-31',1,1659.38,0.08),('2017-01-01','2017-12-31',2,2765.66,0.09),('2017-01-01','2017-12-31',3,5531.31,0.11),
-- 2018
('2018-01-01','2018-12-31',1,1693.72,0.08),('2018-01-01','2018-12-31',2,2822.90,0.09),('2018-01-01','2018-12-31',3,5645.80,0.11),
-- 2019
('2019-01-01','2019-12-31',1,1751.81,0.08),('2019-01-01','2019-12-31',2,2919.72,0.09),('2019-01-01','2019-12-31',3,5839.45,0.11),
-- 2020 jan-fev (flat-rate antes da reforma)
('2020-01-01','2020-02-28',1,1830.29,0.08),('2020-01-01','2020-02-28',2,3050.52,0.09),('2020-01-01','2020-02-28',3,6101.06,0.11),
-- 2020 mar-dez (progressivo pós-reforma EC 103/2019)
('2020-03-01','2020-12-31',1,1045.00,0.075),('2020-03-01','2020-12-31',2,2089.60,0.09),('2020-03-01','2020-12-31',3,3134.40,0.12),('2020-03-01','2020-12-31',4,6101.06,0.14),
-- 2021
('2021-01-01','2021-12-31',1,1100.00,0.075),('2021-01-01','2021-12-31',2,2203.48,0.09),('2021-01-01','2021-12-31',3,3305.22,0.12),('2021-01-01','2021-12-31',4,6433.57,0.14),
-- 2022
('2022-01-01','2022-12-31',1,1212.00,0.075),('2022-01-01','2022-12-31',2,2427.35,0.09),('2022-01-01','2022-12-31',3,3641.03,0.12),('2022-01-01','2022-12-31',4,7087.22,0.14)
ON CONFLICT DO NOTHING;

-- ============================================================
-- SEED: pjecalc_imposto_renda + faixas histórico 2003-2022
-- Fonte: RFB - Tabela progressiva mensal
-- ============================================================

-- Helper: insert IR parent + faixas for each year
-- 2015-2022 (tabela congelada de 2015 a 2022)
INSERT INTO public.pjecalc_imposto_renda (competencia, deducao_dependente, deducao_aposentado_65)
VALUES
  ('2015-04-01', 189.59, 1903.98),
  ('2011-01-01', 157.47, 1566.61),
  ('2009-01-01', 144.20, 1434.59),
  ('2007-01-01', 132.05, 1313.69),
  ('2005-01-01', 117.00, 1164.00),
  ('2003-01-01', 106.00, 1058.00)
ON CONFLICT DO NOTHING;

-- Note: IR faixas need to reference the pjecalc_imposto_renda parent ID
-- Since we can't know the IDs in advance, we use a DO block
DO $$
DECLARE
  v_id uuid;
BEGIN
  -- Check if 2015 IR parent already has faixas
  SELECT id INTO v_id FROM public.pjecalc_imposto_renda WHERE competencia = '2015-04-01' LIMIT 1;
  IF v_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.pjecalc_imposto_renda_faixas WHERE ir_id = v_id) THEN
    INSERT INTO public.pjecalc_imposto_renda_faixas (ir_id, faixa, valor_final, aliquota, parcela_deduzir) VALUES
      (v_id, 1, 1903.98, 0, 0),
      (v_id, 2, 2826.65, 0.075, 142.80),
      (v_id, 3, 3751.05, 0.15, 354.80),
      (v_id, 4, 4664.68, 0.225, 636.13),
      (v_id, 5, 999999999, 0.275, 869.36);
  END IF;

  -- 2011 IR
  SELECT id INTO v_id FROM public.pjecalc_imposto_renda WHERE competencia = '2011-01-01' LIMIT 1;
  IF v_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.pjecalc_imposto_renda_faixas WHERE ir_id = v_id) THEN
    INSERT INTO public.pjecalc_imposto_renda_faixas (ir_id, faixa, valor_final, aliquota, parcela_deduzir) VALUES
      (v_id, 1, 1566.61, 0, 0),
      (v_id, 2, 2347.85, 0.075, 117.49),
      (v_id, 3, 3130.51, 0.15, 293.58),
      (v_id, 4, 3911.63, 0.225, 528.37),
      (v_id, 5, 999999999, 0.275, 723.95);
  END IF;
END $$;


-- ── Migration: 20260330200001_pjecalc_correcao_monetaria_bcb.sql ──

-- Tabela de índices de correção monetária (dados reais BCB)
-- Populada via Edge Function populate-bcb-indices com séries oficiais:
--   IPCA-E (10764), SELIC (4390), INPC (188), TR (7812), IGP-M (189)
-- Período: 2000-01 até presente. ~1573 registros.

CREATE TABLE IF NOT EXISTS pjecalc_correcao_monetaria (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  indice      text        NOT NULL,
  competencia date        NOT NULL,
  valor       numeric,
  acumulado   numeric,
  created_at  timestamptz DEFAULT now(),
  UNIQUE (indice, competencia)
);

CREATE INDEX IF NOT EXISTS idx_pjecalc_correcao_idx_comp
  ON pjecalc_correcao_monetaria (indice, competencia);

